#! /usr/bin/env node    
var CommandLine = require('./lib/Parser').Parser,
	parser = new CommandLine("Command", "Description", "Extra text");

//simplest form
parser.addArgument('foo', 'assign a value to foo');

//with all arguments
parser.addArgument('bar' ,{
	flags : ['b','bar'], //default is name
	desc : "assign a value to foo", //default is ''
	optional : false //default is true
});

parser.registerActions({
	bar : function(value, parser){
		console.log("Bar recieved the value of", value);
	}
});

parser.exec();